# a= int (input("Enter the value:-"))
# b = int (input("Enter the value :-"))
# b= 20
# print (a+b)
# print (a-b)
# print (a/b)
# print (a*b)
# print (a**b)
# print (a<=b)
# print (a%b)
# print (a>=b)
# print (bin(a))
# print(bin(b))
# print (a+b)
A= float(input("Enter the value1:-"))
B= eval(input("Enter the value2:-"))
print(A+B)

c= 99
print(bin(c))